# Generated by Django 3.0.7 on 2020-07-09 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200708_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_posted'),
        ),
    ]
